In [53]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_csv("colresult3.csv", encoding = 'utf-8')

In [54]:
print(df)

          발매가  브랜드  라인  콜라보  month  color_num  col1  col2  col3  col4  col5  \
0      259000    3  21    0      4          1     9     0     0     0     0   
1      259000    3  21    0      4          1     9     0     0     0     0   
2      259000    3  21    0      4          1     9     0     0     0     0   
3      259000    3  21    0      4          1     9     0     0     0     0   
4      259000    3  21    0      4          1     9     0     0     0     0   
...       ...  ...  ..  ...    ...        ...   ...   ...   ...   ...   ...   
43948  209000    5  28   40     10          1     9     0     0     0     0   
43949  209000    5  28   40     10          1     9     0     0     0     0   
43950  209000    5  28   40     10          1     9     0     0     0     0   
43951  209000    5  28   40     10          1     9     0     0     0     0   
43952  209000    5  28   40     10          1     9     0     0     0     0   

       type  day  
0       1.0    0  
1       1.0  

In [55]:
df = df[(df['day'] == 5)]
df = df.sample(frac=1).reset_index(drop=True)
X = df[['발매가', '브랜드', '라인', '콜라보', 'month', 'color_num', 'col1', 'col2', 'col3', 'col4','col5']]
Y = df[['type']]

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X = np.asarray(X).astype(np.int64)

In [57]:
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.4, random_state = 1)

In [58]:
print(train_x)

[[ 0  1  0 ...  0  0  0]
 [ 0 -1 -1 ...  0  0  0]
 [ 1  1  0 ...  0  0  0]
 ...
 [-1 -1  0 ...  1  0  0]
 [ 0 -1 -1 ...  0  0  0]
 [ 0 -1 -1 ...  1  0  0]]


In [59]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class = "multinomial", solver = "lbfgs", C = 10)
model.fit(train_x, train_y)

C:\Users\USER\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=10, multi_class='multinomial')

In [60]:
print(model.score(train_x, train_y))

0.6013986013986014


In [61]:
model.coef_[0]

array([-0.0890606 ,  0.32216589, -0.97328551,  0.11293816, -0.19945257,
       -0.21678549,  0.12106857, -0.07846401,  0.29406328,  0.23543452,
        0.29195507])